### PR TITLE
10/10 work

### PR DESCRIPTION
**Pull request by cooljohnny3**
Started writing unit tests for player and equipment.  Most of the additions are from the googletest folder.  Look at the makefile below  the "My Tests" comment and 2 new unittest files for actual changes.

### CODE REVIEW

**Comment by kyledewey** [comment]
Assigned @kikunojojou

**Comment by kyledewey** [comment]
Additionally assigned @AnanDoh

**Comment by kikunojojou** [comment]
Nothing wrong but I wonder why there wasn't this documentation there in the first place

**Review by AnanDoh — APPROVED** [review]

**Comment by AnanDoh** [comment]
dassalot of lines changed

**Pull request merged**
