### PR TITLE
10/17 work

### PR DESCRIPTION
**Pull request by cooljohnny3**
Some test work for Creature and Player as well as some code changes.

### CODE REVIEW

**Comment by kyledewey** [comment]
Assigned @AshotC

**Comment by kyledewey** [comment]
Additionally assigned @kikunojojou

**Review by AshotC — APPROVED** [review]
You'll start needing some code sooner or later to test actual encounters. What you have here looks fine though.

**Comment by kikunojojou** [comment]
I would personally like some more comments to explain your changes, but it good

**Pull request merged**
